server:
  port: 8084

spring:
  data:
    mongodb:
      database: quiz
      host: localhost
      password: quiz_pwd
      port: 27017
      username: quiz_user

  cloud:
    function:
      definition: consumeQuizAnswers
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          # produce quiz result
          produceQuizResult-out-0:
            producer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
          # consume quiz answers
          consumeQuizAnswers-in-0:
            consumer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bindings:
        produceQuizResult-out-0:
          destination: quizResultTopic
          producer:
            use-native-encoding: true
        consumeQuizAnswers-in-0:
          destination: quizAnswersTopic
          group: QuizMngService